import {Agent} from "../actors/agents/Agent.js";
import {AgentRequest} from "../actors/agents/AgentRequest.js";
import {Job} from "../jobs/Job.js";
import {Action} from "./Action.js";

/* An action whose properties are generated by an agent. run builds a request
   from the job and hands it to the agent's client; the structured result
   becomes the property map. Subclasses decide how the request is composed. */
abstract class AgenticAction extends Action {

    protected agent : Agent;

    constructor(name : string, agent : Agent, description : string = "", id? : string) {
        super(name, agent, description, id);
        this.agent = agent;
        this.run = async (job : Job) =>
            new Map(Object.entries(await this.agent.client.generate(this.requestFor(job))));
    }

    protected abstract requestFor(job : Job) : AgentRequest;

}

export { AgenticAction }
